---
- name: install apache server
  hosts: webserver
  become: yes
  gather_facts: no

  tasks:
          - name: ensure apache is latest version
            yum:
                    name: httpd
                    state: latest

          - name: ensure apache is running
            service:
                    name: httpd
                    state: started


